### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vcmgc27** [blackducksoftware/scmconnector#8]
Hello,

I'm trying to use scmconnector. configured the properties file as given in documentation.
using protex version 7.5.0 so download protex sdk client and utilities 7.5.0 jar files and added it to classpath.

Tried executing this command: ./SCMConnector.sh /home/scanutilities/protex-scm-connector-1.5.0/config_example.properties

Getting this below output with errors.

2017-04-04 02:16:10,077 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorRunner] - SCM Connector utility, standalone mode.
2017-04-04 02:16:10,078 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorRunner] - Loading configuration file from: /home/scanutilities/protex-scm-connector-1.5.0/config_example.properties
2017-04-04 02:16:10,096 INFO (main) [net.jmatrix.eproperties.EProperties] - Loading EProperties version 1.1.0
2017-04-04 02:16:10,285 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: server.list.location, is missing or blank
2017-04-04 02:16:10,286 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: email.smtp.address, is missing or blank
2017-04-04 02:16:10,286 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: email.smtp.to, is missing or blank
2017-04-04 02:16:10,286 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: email.smtp.from, is missing or blank
2017-04-04 02:16:10,286 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: proxy.server, is missing or blank
2017-04-04 02:16:10,287 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: proxy.port, is missing or blank
2017-04-04 02:16:10,287 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: proxy.https.server, is missing or blank
2017-04-04 02:16:10,287 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: proxy.https.port, is missing or blank
2017-04-04 02:16:10,287 WARN (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - Server List location property exists, but empty
2017-04-04 02:16:10,289 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: max.connector.index, is missing or blank
2017-04-04 02:16:10,289 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: perform.scan, is missing or blank
2017-04-04 02:16:10,289 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: copy.analysis.results.from.template, is missing or blank
2017-04-04 02:16:10,289 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - [Optional] property: notification.substitution.0.variable, is missing or blank
2017-04-04 02:16:10,300 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorUtils] - Found host name: ip-172-31-51-103.ec2.internal
2017-04-04 02:16:10,301 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorRunner] - Executing connnectors on: ip-172-31-51-103.ec2.internal
2017-04-04 02:16:10,301 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorConfig] - Setting proxy to false and nulling out the protex directory
2017-04-04 02:16:10,302 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorRunner] - Found connector: NOP (no operation)
2017-04-04 02:16:10,303 WARN (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorPropertyRetriever] - Property is either missing or empty: protex.home_directory
2017-04-04 02:16:10,303 INFO (main) [com.blackducksoftware.tools.scmconnector.integrations.nop.NOPConnector] - Final source destination: /home/blackduck/ca_build
2017-04-04 02:16:10,304 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorRunner] - Processing connector for project: testscm
2017-04-04 02:16:10,304 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ConnectorRunner] - Performing sync of data for project: testscm
2017-04-04 02:16:10,304 INFO (main) [com.blackducksoftware.tools.scmconnector.core.ProtexRunnerImpl] - Creating or finding project: testscm
Exception in thread "main" java.lang.NoClassDefFoundError: com/blackducksoftware/sdk/protex/client/util/ProtexServerProxyV6_3
        at com.blackducksoftware.tools.commonframework.connector.protex.ProtexServerWrapper.<init>(ProtexServerWrapper.java:68)
        at com.blackducksoftware.tools.scmconnector.core.protex.ProjectCreatorFactory.getCreator(ProjectCreatorFactory.java:35)
        at com.blackducksoftware.tools.scmconnector.core.ProtexRunnerImpl.run(ProtexRunnerImpl.java:60)
        at com.blackducksoftware.tools.scmconnector.core.ConnectorRunner.processConnector(ConnectorRunner.java:196)
        at com.blackducksoftware.tools.scmconnector.core.ConnectorRunner.processConnectors(ConnectorRunner.java:247)
        at com.blackducksoftware.tools.scmconnector.core.ConnectorRunner.main(ConnectorRunner.java:104)
Caused by: java.lang.ClassNotFoundException: com.blackducksoftware.sdk.protex.client.util.ProtexServerProxyV6_3
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 6 more

Please help me in resolving this issue.

**Comment by stavvy-akamen** [comment]
Hello,  we really cannot help with modified code that we have no visibility into.   Because the SCM Connector uses the common framework, i suggest you upgrade the CF to used the latest Protex 7.5 jars (release that) and then try again.

**Comment by vcmgc27** [comment]
Hello Ari Kamen,

Guess you haven't read the above issue properly. I haven't modified any code or any jar file from this scmconnector package. Just downloaded the package and added information to config.properties file and ran the command as mentioned in documentation section.

Also, Guess you haven't seen the error mentioned above. Please look into this and let me know, what I can do on this. 

**Please understand, no code or binaries modified in this package. Using as it is out of box**.

Thanks,
Gowtham C
